# Shared constants for the PySide6 application



# Elements and Colors (Rulebook pg. 5)
ELEMENT_COLORS = {
    "Death": "Black",
    "Air": "Blue",
    "Water": "Green",
    "Fire": "Red",
    "Earth": "Yellow",
    "Ivory": "Ivory", # Lack of any elements
    "White": "White"  # Presence of all elements
}

# Terrain Definitions (Name, List of Colors from ELEMENT_COLORS values)
# Rulebook pg. 5
TERRAIN_DATA = [
    ("Coastland", [ELEMENT_COLORS["Air"], ELEMENT_COLORS["Water"]]),
    ("Deadland", [ELEMENT_COLORS["Death"]]),
    ("Flatland", [ELEMENT_COLORS["Air"], ELEMENT_COLORS["Earth"]]),
    ("Highland", [ELEMENT_COLORS["Fire"], ELEMENT_COLORS["Earth"]]),
    ("Swampland", [ELEMENT_COLORS["Water"], ELEMENT_COLORS["Earth"]]),
    ("Feyland", [ELEMENT_COLORS["Water"], ELEMENT_COLORS["Fire"]]),
    ("Wasteland", [ELEMENT_COLORS["Air"], ELEMENT_COLORS["Fire"]]),
]

# Game Phases
PHASE_EXPIRE_EFFECTS = "EXPIRE_EFFECTS"
PHASE_EIGHTH_FACE = "EIGHTH_FACE"
PHASE_DRAGON_ATTACK = "DRAGON_ATTACK"
PHASE_SPECIES_ABILITIES = "SPECIES_ABILITIES"
PHASE_FIRST_MARCH = "FIRST_MARCH"
PHASE_SECOND_MARCH = "SECOND_MARCH"
PHASE_RESERVES = "RESERVES"

TURN_PHASES = [
    PHASE_EXPIRE_EFFECTS,
    PHASE_EIGHTH_FACE,
    PHASE_DRAGON_ATTACK,
    PHASE_SPECIES_ABILITIES,
    PHASE_FIRST_MARCH,
    PHASE_SECOND_MARCH,
    PHASE_RESERVES
]

# March Steps
MARCH_STEP_DECIDE_MANEUVER = "DECIDE_MANEUVER"
MARCH_STEP_AWAITING_MANEUVER_INPUT = "AWAITING_MANEUVER_INPUT"
MARCH_STEP_SELECT_ACTION = "SELECT_ACTION"

MARCH_STEPS = [
    MARCH_STEP_DECIDE_MANEUVER,
    MARCH_STEP_AWAITING_MANEUVER_INPUT,
    MARCH_STEP_SELECT_ACTION
]

# Action Types
ACTION_MELEE = "MELEE"
ACTION_MISSILE = "MISSILE"
ACTION_MAGIC = "MAGIC"

# Action Steps (Sub-steps within an action)
ACTION_STEP_AWAITING_ATTACKER_MELEE_ROLL = "AWAITING_ATTACKER_MELEE_ROLL"
ACTION_STEP_AWAITING_DEFENDER_SAVES = "AWAITING_DEFENDER_SAVES"
ACTION_STEP_AWAITING_ATTACKER_MISSILE_ROLL = "AWAITING_ATTACKER_MISSILE_ROLL" # Example
ACTION_STEP_AWAITING_MAGIC_ROLL = "AWAITING_MAGIC_ROLL" # Example

# Dice Icon Types
ICON_MELEE = "MELEE"
ICON_MISSILE = "MISSILE"
ICON_MAGIC = "MAGIC"
ICON_SAVE = "SAVE"
ICON_ID = "ID"
ICON_SAI = "SAI"
ICON_MANEUVER = "MANEUVER" # Standard maneuver icon
ICON_DRAGON_ATTACK_CLAW = "DRAGON_CLAW"
ICON_DRAGON_ATTACK_BITE = "DRAGON_BITE"
ICON_DRAGON_ATTACK_TAIL = "DRAGON_TAIL"
ICON_DRAGON_BREATH = "DRAGON_BREATH" # Generic, specific type (fire, ice) might be an attribute

# Special Action Icons (SAIs) - Name constants
# These would be keys in a more detailed definition dictionary.
SAI_BULLSEYE = "BULLSEYE"
SAI_DOUBLER = "DOUBLER"
SAI_TRIPLER = "TRIPLER"
SAI_RECRUIT = "RECRUIT"
SAI_MAGIC_BOLT = "MAGIC_BOLT" # Example
# ... add all known SAIs