# Unit data for Dragon Dice species
# Each unit defined as a UnitModel instance

from models.species_model import SPECIES_DATA
from models.unit_model import UnitModel
from models.die_face_model import get_die_faces_for_unit_type


def get_unit_by_id(unit_id: str):
    """Get a unit by its unit_id."""
    for unit in UNIT_DATA:
        if unit.unit_id == unit_id:
            return unit
    return None


# Unit instances
UNIT_DATA = [
    UnitModel(
        unit_id="goblin_thug",
        name="Thug",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="goblin_cutthroat",
        name="Cutthroat",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="goblin_marauder",
        name="Marauder",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="goblin_cannibal",
        name="Cannibal",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="goblin_mugger",
        name="Mugger",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="goblin_ambusher",
        name="Ambusher",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="goblin_filcher",
        name="Filcher",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="goblin_death_naga",
        name="Death Naga",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="goblin_wardog_rider",
        name="Wardog Rider",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="goblin_wolf_rider",
        name="Wolf Rider",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="goblin_leopard_rider",
        name="Leopard Rider",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="goblin_harpy",
        name="Harpy",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="goblin_pelter",
        name="Pelter",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="goblin_slingman",
        name="Slingman",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="goblin_deadeye",
        name="Deadeye",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="goblin_shambler",
        name="Shambler",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="goblin_trickster",
        name="Trickster",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="goblin_hedge_wizard",
        name="Hedge Wizard",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="goblin_death_mage",
        name="Death Mage",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="goblin_troll",
        name="Troll",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["GOBLIN"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="feral_lynx_folk",
        name="Lynx-Folk",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="feral_leopard_folk",
        name="Leopard-Folk",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="feral_tiger_folk",
        name="Tiger-Folk",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="feral_bear_folk",
        name="Bear-Folk",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="feral_hound_folk",
        name="Hound-Folk",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="feral_fox_folk",
        name="Fox-Folk",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="feral_wolf_folk",
        name="Wolf-Folk",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="feral_elephant_folk",
        name="Elephant-Folk",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="feral_antelope_folk",
        name="Antelope-Folk",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="feral_horse_folk",
        name="Horse-Folk",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="feral_buffalo_folk",
        name="Buffalo-Folk",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="feral_lion_folk",
        name="Lion-Folk",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="feral_falcon_folk",
        name="Falcon-Folk",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="feral_hawk_folk",
        name="Hawk-Folk",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="feral_vulture_folk",
        name="Vulture-Folk",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="feral_owl_folk",
        name="Owl-Folk",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="feral_weasel_folk",
        name="Weasel-Folk",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="feral_badger_folk",
        name="Badger-Folk",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="feral_wolverine_folk",
        name="Wolverine-Folk",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="feral_rhino_folk",
        name="Rhino-Folk",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FERAL"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="coral_elf_fighter",
        name="Fighter",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="coral_elf_trooper",
        name="Trooper",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="coral_elf_protector",
        name="Protector",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="coral_elf_coral_giant",
        name="Coral Giant",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="coral_elf_guard",
        name="Guard",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="coral_elf_courier",
        name="Courier",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="coral_elf_herald",
        name="Herald",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="coral_elf_gryphon",
        name="Gryphon",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="coral_elf_horseman",
        name="Horseman",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="coral_elf_knight",
        name="Knight",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="coral_elf_eagle_knight",
        name="Eagle Knight",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="coral_elf_leviathan",
        name="Leviathan",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="coral_elf_bowman",
        name="Bowman",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="coral_elf_archer",
        name="Archer",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="coral_elf_sharpshooter",
        name="Sharpshooter",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="coral_elf_sprite_swarm",
        name="Sprite Swarm",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="coral_elf_evoker",
        name="Evoker",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="coral_elf_conjurer",
        name="Conjurer",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="coral_elf_enchanter",
        name="Enchanter",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="coral_elf_tako",
        name="Tako",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["CORAL_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="dwarf_footman",
        name="Footman",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="dwarf_sergeant",
        name="Sergeant",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="dwarf_warlord",
        name="Warlord",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="dwarf_androsphinx",
        name="Androsphinx",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="dwarf_sentry",
        name="Sentry",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="dwarf_patroller",
        name="Patroller",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="dwarf_skirmisher",
        name="Skirmisher",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="dwarf_behemoth",
        name="Behemoth",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="dwarf_pony_rider",
        name="Pony Rider",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="dwarf_lizard_rider",
        name="Lizard Rider",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="dwarf_mammoth_rider",
        name="Mammoth Rider",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="dwarf_gargoyle",
        name="Gargoyle",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="dwarf_crossbowman",
        name="Crossbowman",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="dwarf_marksman",
        name="Marksman",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="dwarf_crack_shot",
        name="Crack-Shot",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="dwarf_roc",
        name="Roc",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="dwarf_theurgist",
        name="Theurgist",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="dwarf_thaumaturgist",
        name="Thaumaturgist",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="dwarf_wizard",
        name="Wizard",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="dwarf_umber_hulk",
        name="Umber Hulk",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["DWARF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="firewalker_guardian",
        name="Guardian",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="firewalker_watcher",
        name="Watcher",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="firewalker_sentinel",
        name="Sentinel",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="firewalker_fireshadow",
        name="Fireshadow",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="firewalker_explorer",
        name="Explorer",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="firewalker_adventurer",
        name="Adventurer",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="firewalker_expeditioner",
        name="Expeditioner",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="firewalker_genie",
        name="Genie",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="firewalker_shadowchaser",
        name="Shadowchaser",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="firewalker_nightsbane",
        name="Nightsbane",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="firewalker_daybringer",
        name="Daybringer",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="firewalker_gorgon",
        name="Gorgon",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="firewalker_firestarter",
        name="Firestarter",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="firewalker_firemaster",
        name="Firemaster",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="firewalker_firestormer",
        name="Firestormer",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="firewalker_phoenix",
        name="Phoenix",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="firewalker_sunburst",
        name="Sunburst",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="firewalker_sunflare",
        name="Sunflare",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="firewalker_ashbringer",
        name="Ashbringer",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="firewalker_salamander",
        name="Salamander",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FIREWALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="frostwing_advocate",
        name="Advocate",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="frostwing_defender",
        name="Defender",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="frostwing_vindicator",
        name="Vindicator",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="frostwing_cryohydra",
        name="Cryohydra",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="frostwing_hound_master",
        name="Hound Master",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="frostwing_wolf_master",
        name="Wolf Master",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="frostwing_bear_master",
        name="Bear Master",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="frostwing_frost_ogre",
        name="Frost Ogre",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="frostwing_attacker",
        name="Attacker",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="frostwing_assaulter",
        name="Assaulter",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="frostwing_assailer",
        name="Assailer",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="frostwing_remorhaz",
        name="Remorhaz",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="frostwing_destroyer",
        name="Destroyer",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="frostwing_dispatcher",
        name="Dispatcher",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="frostwing_devastator",
        name="Devastator",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="frostwing_wolf_pack",
        name="Wolf Pack",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="frostwing_apprentice",
        name="Apprentice",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="frostwing_magus",
        name="Magus",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="frostwing_magi",
        name="Magi",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="frostwing_yeti",
        name="Yeti",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["FROSTWING"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="swamp_stalker_warmonger",
        name="Warmonger",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="swamp_stalker_ravager",
        name="Ravager",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="swamp_stalker_annihilator",
        name="Annihilator",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="swamp_stalker_crocosaur",
        name="Crocosaur",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="swamp_stalker_striker",
        name="Striker",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="swamp_stalker_raider",
        name="Raider",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="swamp_stalker_invader",
        name="Invader",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="swamp_stalker_mudman",
        name="Mudman",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="swamp_stalker_bog_runner",
        name="Bog Runner",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="swamp_stalker_marsh_swimmer",
        name="Marsh Swimmer",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="swamp_stalker_wave_rider",
        name="Wave Rider",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="swamp_stalker_ormyrr",
        name="Ormyrr",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="swamp_stalker_sprayer",
        name="Sprayer",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="swamp_stalker_stormer",
        name="Stormer",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="swamp_stalker_deluger",
        name="Deluger",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="swamp_stalker_swamp_beast",
        name="Swamp Beast",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="swamp_stalker_bog_adept",
        name="Bog Adept",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="swamp_stalker_marsh_mage",
        name="Marsh Mage",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="swamp_stalker_swamp_wizard",
        name="Swamp Wizard",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="swamp_stalker_swamp_giant",
        name="Swamp Giant",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SWAMP_STALKER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="treefolk_oakling",
        name="Oakling",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="treefolk_oak",
        name="Oak",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="treefolk_oak_lord",
        name="Oak Lord",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="treefolk_darktree",
        name="Darktree",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="treefolk_willowling",
        name="Willowling",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="treefolk_willow",
        name="Willow",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="treefolk_willow_noble",
        name="Willow Noble",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="treefolk_redwood",
        name="Redwood",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="treefolk_nymph",
        name="Nymph",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="treefolk_naiad",
        name="Naiad",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="treefolk_lady_nereid",
        name="Lady Nereid",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="treefolk_satyr",
        name="Satyr",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="treefolk_pineling",
        name="Pineling",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="treefolk_pine",
        name="Pine",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="treefolk_pine_prince",
        name="Pine Prince",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="treefolk_strangle_vine",
        name="Strangle Vine",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="treefolk_hamadryad",
        name="Hamadryad",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="treefolk_dryad",
        name="Dryad",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="treefolk_eldar_dryad",
        name="Eldar Dryad",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="treefolk_unicorn",
        name="Unicorn",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["TREEFOLK"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="undead_zombie",
        name="Zombie",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="undead_wight",
        name="Wight",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="undead_mummy",
        name="Mummy",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="undead_carrion_crawler",
        name="Carrion Crawler",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="undead_skeleton",
        name="Skeleton",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="undead_revenant",
        name="Revenant",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="undead_death_knight",
        name="Death Knight",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="undead_dracolich",
        name="Dracolich",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="undead_wraith",
        name="Wraith",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="undead_spectre",
        name="Spectre",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="undead_ghost",
        name="Ghost",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="undead_fenhound",
        name="Fenhound",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="undead_ghoul",
        name="Ghoul",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="undead_ghast",
        name="Ghast",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="undead_vampire",
        name="Vampire",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="undead_minor_death",
        name="Minor Death",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="undead_apparition",
        name="Apparition",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="undead_heucuva",
        name="Heucuva",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="undead_lich",
        name="Lich",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="undead_skeletal_steed",
        name="Skeletal Steed",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["UNDEAD"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="amazon_warrior",
        name="Warrior",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="amazon_soldier",
        name="Soldier",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="amazon_war_chief",
        name="War Chief",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="amazon_centaur",
        name="Centaur",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="amazon_runner",
        name="Runner",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="amazon_envoy",
        name="Envoy",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="amazon_harbinger",
        name="Harbinger",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="amazon_chimera",
        name="Chimera",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="amazon_charioteer",
        name="Charioteer",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="amazon_battle_rider",
        name="Battle Rider",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="amazon_war_driver",
        name="War Driver",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="amazon_hydra",
        name="Hydra",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="amazon_darter",
        name="Darter",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="amazon_javelineer",
        name="Javelineer",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="amazon_spearer",
        name="Spearer",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="amazon_medusa",
        name="Medusa",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="amazon_seer",
        name="Seer",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="amazon_visionary",
        name="Visionary",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="amazon_oracle",
        name="Oracle",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="amazon_nightmare",
        name="Nightmare",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["AMAZON"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="lava_elf_bladesman",
        name="Bladesman",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="lava_elf_duelist",
        name="Duelist",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="lava_elf_conqueror",
        name="Conqueror",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="lava_elf_beholder",
        name="Beholder",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="lava_elf_scout",
        name="Scout",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="lava_elf_spy",
        name="Spy",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="lava_elf_infiltrator",
        name="Infiltrator",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="lava_elf_drider",
        name="Drider",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="lava_elf_spider_rider",
        name="Spider Rider",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="lava_elf_scorpion_knight",
        name="Scorpion Knight",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="lava_elf_wyvern_rider",
        name="Wyvern Rider",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="lava_elf_hell_hound",
        name="Hell Hound",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="lava_elf_fusilier",
        name="Fusilier",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="lava_elf_dead_shot",
        name="Dead-Shot",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="lava_elf_assassin",
        name="Assassin",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="lava_elf_lurker_in_the_deep",
        name="Lurker in the Deep",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="lava_elf_adept",
        name="Adept",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="lava_elf_warlock",
        name="Warlock",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="lava_elf_necromancer",
        name="Necromancer",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="lava_elf_rakshasa",
        name="Rakshasa",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["LAVA_ELF"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="scalder_singeman",
        name="Singeman",
        unit_type="Heavy Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 1),
    ),
    UnitModel(
        unit_id="scalder_scorcher",
        name="Scorcher",
        unit_type="Heavy Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 2),
    ),
    UnitModel(
        unit_id="scalder_searer",
        name="Searer",
        unit_type="Heavy Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Heavy Melee", 3),
    ),
    UnitModel(
        unit_id="scalder_ettercap",
        name="Ettercap",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="scalder_kindler",
        name="Kindler",
        unit_type="Light Melee",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 1),
    ),
    UnitModel(
        unit_id="scalder_igniter",
        name="Igniter",
        unit_type="Light Melee",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 2),
    ),
    UnitModel(
        unit_id="scalder_charkin",
        name="Charkin",
        unit_type="Light Melee",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Light Melee", 3),
    ),
    UnitModel(
        unit_id="scalder_quickling",
        name="Quickling",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="scalder_dragonne_tender",
        name="Dragonne Tender",
        unit_type="Cavalry",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 1),
    ),
    UnitModel(
        unit_id="scalder_dragonne_rider",
        name="Dragonne Rider",
        unit_type="Cavalry",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 2),
    ),
    UnitModel(
        unit_id="scalder_dragonne_knight",
        name="Dragonne Knight",
        unit_type="Cavalry",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Cavalry", 3),
    ),
    UnitModel(
        unit_id="scalder_unseelie_faerie",
        name="Unseelie Faerie",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="scalder_glower",
        name="Glower",
        unit_type="Missile",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Missile", 1),
    ),
    UnitModel(
        unit_id="scalder_burner",
        name="Burner",
        unit_type="Missile",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Missile", 2),
    ),
    UnitModel(
        unit_id="scalder_blazer",
        name="Blazer",
        unit_type="Missile",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Missile", 3),
    ),
    UnitModel(
        unit_id="scalder_web_bird",
        name="Web Bird",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
    UnitModel(
        unit_id="scalder_sparker",
        name="Sparker",
        unit_type="Magic",
        health=1,
        max_health=1,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Magic", 1),
    ),
    UnitModel(
        unit_id="scalder_smolderer",
        name="Smolderer",
        unit_type="Magic",
        health=2,
        max_health=2,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Magic", 2),
    ),
    UnitModel(
        unit_id="scalder_inferno",
        name="Inferno",
        unit_type="Magic",
        health=3,
        max_health=3,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Magic", 3),
    ),
    UnitModel(
        unit_id="scalder_will_o_wisp",
        name="Will o' Wisp",
        unit_type="Monster",
        health=4,
        max_health=4,
        abilities={},
        species=SPECIES_DATA["SCALDER"],
        die_faces=get_die_faces_for_unit_type("Monster", 4),
    ),
]


# Helper functions for unit data access
# Helper functions for unit data access
def get_units_for_species(species_name: str) -> list:
    """Get all unit instances for a specific species."""
    # Handle both display name and key formats
    return [
        unit
        for unit in UNIT_DATA
        if unit.species.name.upper() == species_name.upper()
        or unit.species.name == species_name
    ]


def get_unit_by_id(unit_type_id: str):
    """Get a specific unit instance by its type_id."""
    for unit in UNIT_DATA:
        if unit.unit_id == unit_type_id:
            return unit
    return None


def get_all_species() -> list:
    """Get a list of all species names."""
    species_names = set()
    for unit in UNIT_DATA:
        species_names.add(unit.species.name)
    return list(species_names)


def get_units_by_class(unit_class_type: str) -> list:
    """Get all units of a specific class type across all species."""
    return [unit for unit in UNIT_DATA if unit.unit_type == unit_class_type]


def validate_unit_data_integrity() -> bool:
    """Validate the integrity of all unit data. Returns True if all data is valid."""
    valid_unit_classes = [
        "Heavy Melee",
        "Light Melee",
        "Cavalry",
        "Missile",
        "Magic",
        "Monster",
    ]
    valid_health_values = [1, 2, 3, 4]

    unit_ids = set()

    for unit in UNIT_DATA:
        # Check that it's a UnitModel instance
        if not isinstance(unit, UnitModel):
            print(f"ERROR: Unit is not a UnitModel instance: {unit}")
            return False

        # Check for duplicate IDs
        unit_id = unit.unit_id
        if unit_id in unit_ids:
            print(f"ERROR: Duplicate unit type_id: {unit_id}")
            return False
        unit_ids.add(unit_id)

        # Validate field values
        if not isinstance(unit.name, str) or not unit.name.strip():
            print(f"ERROR: Invalid name in {unit_id}")
            return False

        if unit.max_health not in valid_health_values:
            print(f"ERROR: Invalid max_health {unit.max_health} in {unit_id}")
            return False

        if unit.unit_type not in valid_unit_classes:
            print(f"ERROR: Invalid unit_type '{unit.unit_type}' in {unit_id}")
            return False

        # Validate species reference
        if not hasattr(unit.species, "name"):
            print(f"ERROR: Invalid species reference in {unit_id}")
            return False

    print(f"✓ All {len(unit_ids)} unit instances validated successfully")
    return True
